name: identity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.20
  flutter_bloc: ^9.0.0
  google_fonts: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  geolocator: ^13.0.2
  geolocator_web: ^4.1.1
  http: ^1.3.0
  intl: ^0.19.0
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  flutter_launcher_icons: ^0.14.3
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.4
  cloud_firestore: ^5.6.5
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  flutter_any_logo: ^1.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dropdown_button2: ^2.3.9
  file_picker: ^9.2.1
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/identity_logo_launcher.png"
  adaptive_icon_background: "#141D2B"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/rive_motion/identity_dark_mode_splash.riv
    - assets/rive_motion/identity_light_mode_splash.riv
    - assets/rive_motion/identity_success_registration.riv
    - assets/rive_motion/searching.riv
