name: identity
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.20
  flutter_bloc: ^9.0.0
  google_fonts: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  geolocator: ^13.0.2
  http: ^1.3.0
  intl: ^0.20.2
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/image/identity_logo_launcher.png"
  adaptive_icon_background: "#141D2B"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/rive_motion/identity_dark_mode_splash.riv
    - assets/rive_motion/identity_light_mode_splash.riv
    - assets/rive_motion/searching.riv
