// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_0CUxLJ253WrrU1mRsUj1u0MF6qBJS0A',
    appId: '1:294941814321:web:d2cb264d7bc86fad7c6f10',
    messagingSenderId: '294941814321',
    projectId: 'identity-f153b',
    authDomain: 'identity-f153b.firebaseapp.com',
    storageBucket: 'identity-f153b.firebasestorage.app',
    measurementId: 'G-G62DD2W22P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnSGNnvGaFg_IRe61e7MpwohuB06CZysI',
    appId: '1:294941814321:android:20980ff4bcbc4d5d7c6f10',
    messagingSenderId: '294941814321',
    projectId: 'identity-f153b',
    storageBucket: 'identity-f153b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkRRp27DinlBrsne2j8gM6bhMJhA6aq4U',
    appId: '1:294941814321:ios:000c3860252984ea7c6f10',
    messagingSenderId: '294941814321',
    projectId: 'identity-f153b',
    storageBucket: 'identity-f153b.firebasestorage.app',
    iosBundleId: 'com.example.identity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkRRp27DinlBrsne2j8gM6bhMJhA6aq4U',
    appId: '1:294941814321:ios:000c3860252984ea7c6f10',
    messagingSenderId: '294941814321',
    projectId: 'identity-f153b',
    storageBucket: 'identity-f153b.firebasestorage.app',
    iosBundleId: 'com.example.identity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_0CUxLJ253WrrU1mRsUj1u0MF6qBJS0A',
    appId: '1:294941814321:web:61126fad88a0934f7c6f10',
    messagingSenderId: '294941814321',
    projectId: 'identity-f153b',
    authDomain: 'identity-f153b.firebaseapp.com',
    storageBucket: 'identity-f153b.firebasestorage.app',
    measurementId: 'G-D4JKJ3BD2H',
  );
}
